INSERT INTO amenities (name, code, applicable_type) VALUES
    ('Parking', 'PARKING', 'BOTH'),
    ('Valet Parking', 'VALET_PARKING', 'BOTH'),
    ('Air Conditioning', 'AIR_CONDITIONING', 'BOTH'),
    ('WiFi', 'WIFI', 'BOTH'),
    ('Power Backup', 'POWER_BACKUP', 'BOTH'),
    ('CCTV Security', 'CCTV_SECURITY', 'BOTH'),
    ('Wheelchair Accessible', 'WHEELCHAIR_ACCESSIBLE', 'BOTH'),
    ('Lift', 'LIFT', 'BOTH'),
    ('Restaurant', 'RESTAURANT', 'HOTEL'),
    ('Room Service', 'ROOM_SERVICE', 'HOTEL'),
    ('24/7 Front Desk', 'FRONT_DESK_24_7', 'HOTEL'),
    ('Gym / Fitness Center', 'GYM', 'HOTEL'),
    ('Spa', 'SPA', 'HOTEL'),
    ('Swimming Pool', 'SWIMMING_POOL', 'HOTEL'),
    ('Breakfast Included', 'BREAKFAST_INCLUDED', 'HOTEL'),
    ('Laundry Service', 'LAUNDRY', 'HOTEL'),
    ('Pet Friendly', 'PET_FRIENDLY', 'HOTEL'),
    ('Stage', 'STAGE', 'MARRIAGE_HALL'),
    ('DJ / Sound System', 'DJ_SOUND', 'MARRIAGE_HALL'),
    ('Bride & Groom Rooms', 'BRIDE_GROOM_ROOMS', 'MARRIAGE_HALL'),
    ('Catering', 'CATERING', 'MARRIAGE_HALL'),
    ('In-house Kitchen', 'IN_HOUSE_KITCHEN', 'MARRIAGE_HALL'),
    ('Outside Catering Allowed', 'OUTSIDE_CATERING', 'MARRIAGE_HALL'),
    ('Decoration', 'DECORATION', 'MARRIAGE_HALL'),
    ('Dance Floor', 'DANCE_FLOOR', 'MARRIAGE_HALL'),
    ('Lawn / Garden', 'GARDEN', 'MARRIAGE_HALL'),
    ('Projector / LED Screen', 'PROJECTOR', 'MARRIAGE_HALL'),
    ('Photography Allowed', 'PHOTOGRAPHY', 'MARRIAGE_HALL'),
    ('Alcohol Allowed', 'ALCOHOL_ALLOWED', 'MARRIAGE_HALL'),
    ('Fireworks Allowed', 'FIREWORKS_ALLOWED', 'MARRIAGE_HALL')
ON CONFLICT (name) DO UPDATE
    SET code = excluded.code, applicable_type = excluded.applicable_type;
